### PR TITLE
Small fixes to speech color changer

### PR DESCRIPTION
**Pull request by luka-zitnik**
https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API and https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/continuous and https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition should probably be updated as well.

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
This seems to work fine; thanks for the contribution.

**Comment by chrisdavidmills** [comment]
I updated the pages you cited too.

**Comment by luka-zitnik** [comment]
@chrisdavidmills Cool! I followed you with another small fix to https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API Does updating live demos means syncing gh-pages?

**Comment by chrisdavidmills** [comment]
@luka-zitnik ah, thanks for catching that.

So yes, the live demos on GitHub pages are being taken form the gh-pages branch.

I'm not sure if there are any valuable changes on the gh-pages branch that aren't on master, so I've tried updating the repo so that it serves the GitHub pages live demos from the master branch instead.

If nothing breaks too horribly, then I'm considering just deleting the gh-pages branch, to avoid further confusion. Good idea?

**Comment by luka-zitnik** [comment]
Perfect! :+1:

**Comment by chrisdavidmills** [comment]
Cool. The versions on master seem fine, so I'll go ahead and delete the gh-pages branch.

**Pull request merged**
